using Orquestra.Application.Drafts;
using Orquestra.Application.Security;
internal static class PublicationEndpoints
{
 public static void MapPublicationEndpoints(this WebApplication app)
 {
  var group=app.MapGroup("/workspace").RequireRateLimiting("session");
  group.AddEndpointFilter(async(invocation,next)=>{var c=invocation.HttpContext;var config=c.RequestServices.GetRequiredService<IConfiguration>();if(!config.GetValue<bool>("Workspace:Enabled")||!config.GetValue<bool>("Workspace:PublicationsEnabled"))throw new WorkspaceException(503,"publication_disabled","Publicação do workspace desabilitada");if(c.Request.Headers.Authorization.Count!=1)throw new SessionRejectedException(401,"session_invalid","Autenticação necessária");var actor=await c.RequestServices.GetRequiredService<SessionAuthenticator>().AuthenticateAsync(c.Request.Headers.Authorization[0],c.RequestAborted);if(!actor.Permissions.IsSupersetOf(new[]{"tela_pipelines","tela_jobs"}))throw new WorkspaceException(403,"permission_denied","Permissão de consulta necessária");if(c.Request.Method!="GET"){if(!config.GetValue<bool>("Workspace:DraftsEnabled"))throw new WorkspaceException(503,"drafts_disabled","Edição de rascunhos desabilitada");if(actor.SessionHash is null)throw new WorkspaceException(401,"bearer_required","Sessão Bearer necessária");if(!actor.Permissions.Contains("acao_editar"))throw new WorkspaceException(403,"permission_denied","Permissão de edição necessária");if((c.Request.Path.Value!.EndsWith("/publish")||c.Request.Path.Value!.EndsWith("/retry"))&&!actor.Permissions.Contains("acao_publicar"))throw new WorkspaceException(403,"permission_denied","Permissão de publicação necessária");}c.Items["publicationActor"]=actor;return await next(invocation);});
  group.MapPost("/drafts/{id:guid}/validate",async(Guid id,HttpContext c,IDraftRepository drafts,LegacyPublicationValidationClient validator,CancellationToken ct)=>{var draft=await drafts.GetAsync(id,(WorkspacePrincipal)c.Items["publicationActor"]!,ct);var result=PublicationValidationRules.Validate(draft);return Results.Json(result.Valid?await validator.ValidateAsync(id,draft.Revision,c.Request.Headers.Authorization[0]!,ct):result);});
  group.MapPost("/drafts/{id:guid}/publish",async(Guid id,HttpContext c,IDraftRepository drafts,IPublicationRepository publications,LegacyPublicationValidationClient validator,CancellationToken ct)=>{var body=await DraftEndpoints.Body<PublicationCommand>(c,ct);var draft=await drafts.GetAsync(id,(WorkspacePrincipal)c.Items["publicationActor"]!,ct);var previous=await publications.PublicationsAsync(id,ct);if(!previous.Any(o=>o.OperationId==body.OperationId)&&draft.Revision==body.ExpectedRevision){var result=PublicationValidationRules.Validate(draft);if(!result.Valid)throw new WorkspaceException(422,"publication_invalid","Corrija os diagnósticos antes de publicar");var full=await validator.ValidateAsync(id,draft.Revision,c.Request.Headers.Authorization[0]!,ct);if(!full.Valid)throw new WorkspaceException(422,"publication_invalid","Corrija os diagnósticos antes de publicar");}return Results.Json(await publications.PublishAsync(id,body,(WorkspacePrincipal)c.Items["publicationActor"]!,ct),statusCode:202);});
  group.MapPost("/publications/{id:guid}/retry",async(Guid id,HttpContext c,IPublicationRepository repository,CancellationToken ct)=>Results.Json(await repository.RetryAsync(id,await DraftEndpoints.Body<PublicationCommand>(c,ct),(WorkspacePrincipal)c.Items["publicationActor"]!,ct),statusCode:202));
  group.MapGet("/drafts/{id:guid}/publications",async(Guid id,IPublicationRepository repository,CancellationToken ct)=>Results.Json(await repository.PublicationsAsync(id,ct)));
  group.MapGet("/publications/{id:guid}",async(Guid id,IPublicationRepository repository,CancellationToken ct)=>Results.Json(await repository.PublicationAsync(id,ct)));
  group.MapGet("/pipeline-versions",async(string name,IPublicationRepository repository,CancellationToken ct)=>Results.Json(await repository.VersionsAsync(name,ct)));
  group.MapPost("/pipeline-restores",async(string name,HttpContext c,IPublicationRepository repository,CancellationToken ct)=>Results.Json(await repository.RestoreAsync(name,(await DraftEndpoints.Body<RestoreVersion>(c,ct)).VersionId,(WorkspacePrincipal)c.Items["publicationActor"]!,ct),statusCode:201));
 }
}
