using System.Data;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using Orquestra.Application.Drafts;
using Orquestra.Application.Security;
using Orquestra.Domain.Flows;
namespace Orquestra.Infrastructure.Drafts;
public sealed partial class SqlDraftRepository
{
 public async Task<bool> PublicationSchemaAsync(CancellationToken ct)=>await Run(async(c,t)=>{await using var cmd=Command(c,t,"SELECT CASE WHEN OBJECT_ID('dbo.etl_workspace_publicacao','U') IS NOT NULL AND OBJECT_ID('dbo.sp_workspace_active_hash','P') IS NOT NULL THEN 1 ELSE 0 END");return (int)(await cmd.ExecuteScalarAsync(ct))! ==1;},ct);
 private static async Task<string?> ActiveHash(SqlConnection c,SqlTransaction t,string name,CancellationToken ct){await using var cmd=Command(c,t,"EXEC dbo.sp_workspace_active_hash @name",("@name",name));var value=await cmd.ExecuteScalarAsync(ct);return value is null or DBNull?null:(string)value;}
 private static async Task CaptureBaseHash(SqlConnection c,SqlTransaction t,Guid id,string name,CancellationToken ct){await using var exists=Command(c,t,"SELECT COL_LENGTH('dbo.etl_workspace_rascunho','base_active_hash')");if(await exists.ExecuteScalarAsync(ct) is null or DBNull)return;var hash=await ActiveHash(c,t,name,ct);await using var set=Command(c,t,"UPDATE dbo.etl_workspace_rascunho SET base_active_hash=@hash WHERE draft_id=@id",("@hash",hash),("@id",id));await set.ExecuteNonQueryAsync(ct);}
 private static async Task NoPendingPublication(SqlConnection c,SqlTransaction t,Guid id,CancellationToken ct,bool allowFailed=false){await using var schema=Command(c,t,"SELECT OBJECT_ID('dbo.etl_workspace_publicacao','U')");if(await schema.ExecuteScalarAsync(ct) is null or DBNull)return;await using var pending=Command(c,t,"SELECT TOP(1) o.operation_id FROM dbo.etl_workspace_publicacao o LEFT JOIN dbo.etl_workspace_pipeline p ON p.pending_operation_id=o.operation_id WHERE o.draft_id=@id AND (o.estado NOT IN('publicado','erro') OR (@allowFailed=0 AND p.pipeline_name IS NOT NULL))",("@id",id),("@allowFailed",allowFailed?1L:0L));if(await pending.ExecuteScalarAsync(ct) is not null)throw Conflict("publication_pending","Publicação em andamento; aguarde a confirmação");}
 public Task<Publication> PublishAsync(Guid id,PublicationCommand request,WorkspacePrincipal actor,CancellationToken ct)=>Run(async(c,t)=>{
  if(!actor.Permissions.Contains("acao_publicar"))throw new WorkspaceException(403,"permission_denied","Permissão de publicação necessária");
  await CurrentSession(c,t,actor,ct);if(request.OperationId==Guid.Empty)DraftValidation.Invalid("Identificador da operação obrigatório");
  var draft=await Load(c,t,id,true,ct);
  await using(var old=Command(c,t,"SELECT operation_id,revision,fence,draft_id FROM dbo.etl_workspace_publicacao WITH(UPDLOCK,HOLDLOCK) WHERE operation_id=@operation OR (draft_id=@id AND revision=@revision)",("@operation",request.OperationId),("@id",id),("@revision",request.ExpectedRevision))){await using var r=await old.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct)){if(r.GetGuid(0)!=request.OperationId||r.GetInt64(1)!=request.ExpectedRevision||r.GetInt64(2)!=request.Fence||r.GetGuid(3)!=id)throw Conflict("operation_conflict","Operação já registrada com outro comando");await r.DisposeAsync();return await ReadPublication(c,t,request.OperationId,ct);}}
  if(draft.State!="ativo")throw Conflict("draft_closed","Rascunho encerrado");Revision(draft,request.ExpectedRevision);await OwnedLease(c,t,id,request.Fence,actor,ct);
  var validation=PublicationValidationRules.Validate(draft);if(!validation.Valid)throw new WorkspaceException(422,"publication_invalid","Corrija os diagnósticos antes de publicar");
  var name=draft.PipelineName;
  // Mesmo row lock usado por entrada do motor e proteção SQL das fontes.
  await using(var owner=Command(c,t,"SELECT pipeline_name FROM dbo.etl_workspace_pipeline WITH(UPDLOCK,HOLDLOCK) WHERE pipeline_name=@name",("@name",name)))await owner.ExecuteScalarAsync(ct);
  await NoPendingPublication(c,t,id,ct,true);
  string? correctiveHash=null;
  await using(var pending=Command(c,t,"SELECT o.draft_id,o.estado,COALESCE(o.projection_hash,o.inherited_projection_hash) FROM dbo.etl_workspace_pipeline p JOIN dbo.etl_workspace_publicacao o ON o.operation_id=p.pending_operation_id WHERE p.pipeline_name=@name",("@name",name)))
  {await using var row=await pending.ExecuteReaderAsync(ct);if(await row.ReadAsync(ct)){if(row.GetGuid(0)!=id||row.GetString(1)!="erro"||row.IsDBNull(2))throw Conflict("publication_pending","Outra publicação controla este pipeline");correctiveHash=row.GetString(2);}}
  await using(var running=Command(c,t,"SELECT TOP(1) run_id FROM dbo.etl_workspace_execucao WITH(UPDLOCK,HOLDLOCK) WHERE pipeline_name=@name AND ativa=1",("@name",name)))if(await running.ExecuteScalarAsync(ct) is not null)throw Conflict("execution_active","Pipeline possui execução ativa");
  // Telemetria legada também é autoridade; não confundir ausência com inatividade.
  await using(var running=Command(c,t,"SELECT TOP(1) pipeline_name FROM dbo.etl_pipeline_execucao WITH(UPDLOCK,HOLDLOCK) WHERE pipeline_name=@name AND status IN('EXECUTANDO','RUNNING','QUEUED','AGUARDANDO','AGUARDANDO_DEPENDENCIA')",("@name",name)))if(await running.ExecuteScalarAsync(ct) is not null)throw Conflict("execution_active","Pipeline possui execução ativa ou pendente");
  var actual=await ActiveHash(c,t,name,ct);string? expected;
  await using(var baseHash=Command(c,t,"SELECT base_active_hash FROM dbo.etl_workspace_rascunho WHERE draft_id=@id",("@id",id))){var v=await baseHash.ExecuteScalarAsync(ct);expected=v is null or DBNull?null:(string)v;}
  if(correctiveHash is not null)expected=correctiveHash;
  if(draft.BaseVersionId is not null&&expected is null)throw Conflict("base_hash_missing","Rascunho importado antes da F4; preserve suas alterações e reimporte a base antes de publicar");
  if(actual!=expected)throw Conflict("active_hash_conflict","Configuração publicada mudou desde a criação do rascunho; reimporte a base");
  var version=Guid.NewGuid();var definition=JsonSerializer.Serialize(draft.Definition,DraftValidation.Json);var layout=JsonSerializer.Serialize(draft.Layout,DraftValidation.Json);var hash=Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(definition+"\n"+layout)));
  await using(var insert=Command(c,t,"INSERT dbo.etl_workspace_versao(version_id,pipeline_name,numero,origem,definition_json,layout_json,content_hash,criada_por) SELECT @version,@name,ISNULL(MAX(numero),0)+1,'publicada',@definition,@layout,@hash,@actor FROM dbo.etl_workspace_versao WITH(UPDLOCK,HOLDLOCK) WHERE pipeline_name=@name",("@version",version),("@name",name),("@definition",definition),("@layout",layout),("@hash",hash),("@actor",actor.Matricula)))await insert.ExecuteNonQueryAsync(ct);
  await using(var insert=Command(c,t,"INSERT dbo.etl_workspace_publicacao(operation_id,draft_id,version_id,pipeline_name,revision,fence,ator,expected_active_hash,inherited_projection_hash,factory_run_id) VALUES(@operation,@id,@version,@name,@revision,@fence,@actor,@hash,@inherited,@run)",("@operation",request.OperationId),("@id",id),("@version",version),("@name",name),("@revision",draft.Revision),("@fence",request.Fence),("@actor",actor.Matricula),("@hash",expected),("@inherited",correctiveHash),("@run","workspace_"+request.OperationId.ToString("N"))))await insert.ExecuteNonQueryAsync(ct);
  await using(var manage=Command(c,t,"UPDATE dbo.etl_workspace_pipeline SET pending_operation_id=@operation WHERE pipeline_name=@name; IF @@ROWCOUNT=0 INSERT dbo.etl_workspace_pipeline(pipeline_name,pending_operation_id) VALUES(@name,@operation)",("@operation",request.OperationId),("@name",name)))await manage.ExecuteNonQueryAsync(ct);
  await using(var audit=Command(c,t,"INSERT dbo.etl_workspace_evento(entidade_id,ator,acao,revision,operation_id) VALUES(@id,@actor,'solicitar_publicacao',@revision,@operation)",("@id",id),("@actor",actor.Matricula),("@revision",draft.Revision),("@operation",request.OperationId)))await audit.ExecuteNonQueryAsync(ct);
  return await ReadPublication(c,t,request.OperationId,ct);
 },ct);
 public Task<Publication> RetryAsync(Guid operation,PublicationCommand request,WorkspacePrincipal actor,CancellationToken ct)=>Run(async(c,t)=>{
  if(!actor.Permissions.Contains("acao_publicar"))throw new WorkspaceException(403,"permission_denied","Permissão de publicação necessária");await CurrentSession(c,t,actor,ct);
  var op=await ReadPublication(c,t,operation,ct);if(request.OperationId!=operation)throw Conflict("operation_conflict","Identificador de operação divergente");var draft=await Load(c,t,op.DraftId,true,ct);Revision(draft,request.ExpectedRevision);if(op.Revision!=draft.Revision)throw Conflict("revision_conflict","Rascunho mudou desde a publicação");await OwnedLease(c,t,draft.DraftId,request.Fence,actor,ct);
  if(op.State!="erro")return op;
  await using(var lockOwner=Command(c,t,"SELECT pending_operation_id FROM dbo.etl_workspace_pipeline WITH(UPDLOCK,HOLDLOCK) WHERE pipeline_name=@name",("@name",op.PipelineName))){var owner=await lockOwner.ExecuteScalarAsync(ct);if(owner is Guid other&&other!=operation)throw Conflict("publication_pending","Outra publicação controla este pipeline");}
  await using(var retry=Command(c,t,"UPDATE dbo.etl_workspace_pipeline SET pending_operation_id=@operation WHERE pipeline_name=@name; IF @@ROWCOUNT=0 INSERT dbo.etl_workspace_pipeline(pipeline_name,pending_operation_id) VALUES(@name,@operation); UPDATE dbo.etl_workspace_publicacao SET estado=CASE WHEN projection_hash IS NULL THEN 'pendente' ELSE 'projetado' END,retry_requested=1,ator=@actor,erro_resumido=NULL,atualizada_em=SYSUTCDATETIME() WHERE operation_id=@operation",("@operation",operation),("@name",op.PipelineName),("@actor",actor.Matricula)))await retry.ExecuteNonQueryAsync(ct);
  await using(var audit=Command(c,t,"INSERT dbo.etl_workspace_evento(entidade_id,ator,acao,revision,operation_id) VALUES(@id,@actor,'retomar_publicacao',@revision,@operation)",("@id",draft.DraftId),("@actor",actor.Matricula),("@revision",draft.Revision),("@operation",operation)))await audit.ExecuteNonQueryAsync(ct);return await ReadPublication(c,t,operation,ct);
 },ct);
 public Task<IReadOnlyList<Publication>> PublicationsAsync(Guid draft,CancellationToken ct)=>Run<IReadOnlyList<Publication>>(async(c,t)=>{await using var cmd=Command(c,t,"SELECT TOP(20) operation_id FROM dbo.etl_workspace_publicacao WHERE draft_id=@id ORDER BY criada_em DESC",("@id",draft));var ids=new List<Guid>();await using(var r=await cmd.ExecuteReaderAsync(ct)){while(await r.ReadAsync(ct))ids.Add(r.GetGuid(0));}var result=new List<Publication>();foreach(var id in ids)result.Add(await ReadPublication(c,t,id,ct));return result;},ct);
 public Task<Publication> PublicationAsync(Guid id,CancellationToken ct)=>Run((c,t)=>ReadPublication(c,t,id,ct),ct);
 private static async Task<Publication> ReadPublication(SqlConnection c,SqlTransaction t,Guid id,CancellationToken ct){await using var cmd=Command(c,t,"SELECT operation_id,draft_id,version_id,pipeline_name,revision,estado,tentativas,erro_resumido,criada_em,atualizada_em,CASE WHEN projection_hash IS NULL AND inherited_projection_hash IS NULL THEN CAST(0 AS BIT) ELSE CAST(1 AS BIT) END FROM dbo.etl_workspace_publicacao WHERE operation_id=@id",("@id",id));await using var r=await cmd.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))throw new WorkspaceException(404,"publication_not_found","Publicação não encontrada");return new(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetString(3),r.GetInt64(4),r.GetString(5),r.GetInt32(6),r.IsDBNull(7)?null:r.GetString(7),Utc(r.GetDateTime(8)),Utc(r.GetDateTime(9)),r.GetBoolean(10));}
 public Task<IReadOnlyList<PublishedVersion>> VersionsAsync(string name,CancellationToken ct)=>Run<IReadOnlyList<PublishedVersion>>(async(c,t)=>{DraftValidation.Name(name);await using var cmd=Command(c,t,"SELECT TOP(100) v.version_id,v.numero,v.origem,v.content_hash,v.definition_json,v.layout_json,v.criada_por,v.criada_em,COALESCE(o.estado,'importada') FROM dbo.etl_workspace_versao v LEFT JOIN dbo.etl_workspace_publicacao o ON o.version_id=v.version_id WHERE v.pipeline_name=@name ORDER BY v.numero DESC",("@name",name));await using var r=await cmd.ExecuteReaderAsync(ct);var result=new List<PublishedVersion>();while(await r.ReadAsync(ct))result.Add(new(r.GetGuid(0),r.GetInt32(1),r.GetString(2),r.GetString(3),JsonSerializer.Deserialize<PipelineDefinition>(r.GetString(4),DraftValidation.Json)!,JsonSerializer.Deserialize<FlowLayout>(r.GetString(5),DraftValidation.Json)!,r.GetString(6),Utc(r.GetDateTime(7)),r.GetString(8)));return result;},ct);
 public Task<Draft> RestoreAsync(string name,Guid version,WorkspacePrincipal actor,CancellationToken ct)=>Run(async(c,t)=>{await CurrentSession(c,t,actor,ct);DraftValidation.Name(name);await using var cmd=Command(c,t,"SELECT v.definition_json,v.layout_json FROM dbo.etl_workspace_versao v JOIN dbo.etl_workspace_publicacao o ON o.version_id=v.version_id WHERE v.version_id=@version AND v.pipeline_name=@name AND o.estado='publicado'",("@version",version),("@name",name));PipelineDefinition definition;FlowLayout layout;await using(var r=await cmd.ExecuteReaderAsync(ct)){if(!await r.ReadAsync(ct))throw new WorkspaceException(404,"version_not_found","Versão publicada não encontrada");definition=JsonSerializer.Deserialize<PipelineDefinition>(r.GetString(0),DraftValidation.Json)!;layout=JsonSerializer.Deserialize<FlowLayout>(r.GetString(1),DraftValidation.Json)!;}var imported=await Insert(c,t,definition,layout,version,[],actor,ct);await CaptureBaseHash(c,t,imported.DraftId,name,ct);return imported;},ct);
}
