import { useId, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { apiFetch } from '../../lib/api'
import { Input, Select } from '../ui/Input'
import { Button } from '../ui/Button'
import { SCHEDULE_TYPES, SCHEDULE_LABELS, DOW_LABELS, MAX_MONTH_DAYS, hourlyTimes, parseMonthDaysTimes, parseCustomTimes } from '../pipelines/pipelineUtils'
import { text } from '../../lib/workspace'

export function WorkspaceCatalogFields({project,domain,editable,onChange}:{project:string;domain:string;editable:boolean;onChange:(field:string,value:string)=>void}) {
 const id=useId()
 const projects=useQuery<{projects:string[]}>({queryKey:['pipeline-projects'],queryFn:()=>apiFetch('/pipelines/projects'),staleTime:300000})
 const domains=useQuery<{domains:string[]}>({queryKey:['pipeline-domains'],queryFn:()=>apiFetch('/pipelines/domains'),staleTime:300000})
 return <><Select label="Projeto" value={project} disabled={!editable||projects.isPending} onChange={e=>onChange('project_name',e.target.value)}><option value="">{projects.isPending?'Carregando projetos…':'Selecione um projeto'}</option>{project&&!projects.data?.projects.includes(project)&&<option value={project}>{project}</option>}{projects.data?.projects.map(p=><option key={p} value={p}>{p}</option>)}</Select><div><Input label="Domínio" list={id} value={domain} readOnly={!editable} onChange={e=>onChange('domain',e.target.value.toUpperCase())} ajuda="Selecione um domínio existente ou informe um novo, como no cadastro anterior."/><datalist id={id}>{domains.data?.domains.map(d=><option key={d} value={d}/>)}</datalist></div>{(projects.isError||domains.isError)&&<p role="alert" className="text-sm text-red-700 dark:text-red-400 sm:col-span-2">Não foi possível consultar os cadastros. <button type="button" className="underline" onClick={()=>{projects.refetch();domains.refetch()}}>Tentar novamente</button></p>}</>
}

export function WorkspaceScheduleFields({value,editable,onChange}:{value:Record<string,unknown>;editable:boolean;onChange:(next:Record<string,unknown>)=>void}) {
 const [hourly,setHourly]=useState(false)
 const [window,setWindow]=useState({intervalH:2,startH:8,endH:18,minute:0})
 const kind=hourly&&value.schedule_type==='custom'?'hourly_n':text(value.schedule_type)||'on_demand'
 const entries=parseMonthDaysTimes(text(value.dias_horarios_mes))
 const calendars=useQuery<{calendarios:{calendario_nome:string}[]}>({queryKey:['agenda-calendarios'],queryFn:()=>apiFetch('/agenda/calendarios'),staleTime:300000,enabled:editable})
 const patch=(next:Record<string,unknown>)=>onChange({...value,...next})
 const storeEntries=(items:typeof entries)=>JSON.stringify(items.map(x=>({dia:x.dia,horarios:x.horariosRaw.split(',').map(t=>t.trim())})))
 function setKind(type:string){
  setHourly(type==='hourly_n')
  const next={...value,schedule_type:type,scheduled_time:text(value.scheduled_time)||'06:00:00',schedule_dow:1,schedule_dom:1,horarios_especificos:null,dias_semana:null,dias_horarios_mes:null}
  if(type==='hourly_n'){const times=hourlyTimes({type,hour:6,dow:1,dom:1,customTimes:'',weekdays:[],businessDaysOnly:false,...window});onChange({...next,schedule_type:'custom',horarios_especificos:times.join(','),scheduled_time:times[0]+':00'})}
  else if(type==='custom')onChange({...next,horarios_especificos:'06:00'})
  else if(type==='monthly_days_times')onChange({...next,dias_horarios_mes:JSON.stringify([{dia:1,horarios:['06:00']}])})
  else onChange(next)
 }
 function updateWindow(field:keyof typeof window,raw:string){const max=field==='minute'?59:23;const min=field==='intervalH'?1:0;const next={...window,[field]:Math.min(max,Math.max(min,Number(raw)||0))};setWindow(next);const times=hourlyTimes({type:'hourly_n',hour:6,dow:1,dom:1,customTimes:'',weekdays:[],businessDaysOnly:false,...next});patch({horarios_especificos:times.join(','),scheduled_time:(times[0]||'00:00')+':00'})}
 return <fieldset className="space-y-3 min-w-0"><legend className="text-sm font-medium text-ink mb-3">Agendamento</legend><Select label="Tipo de agendamento" value={kind} disabled={!editable} onChange={e=>setKind(e.target.value)}>{SCHEDULE_TYPES.map(t=><option key={t} value={t}>{SCHEDULE_LABELS[t]}</option>)}</Select>
 {kind==='on_demand'?<p className="text-xs text-dim">Executado manualmente, sem disparo automático por horário.</p>:<>
 {kind==='hourly_n'?<div className="grid sm:grid-cols-2 gap-3">{([['intervalH','A cada quantas horas?',1,23],['startH','Hora inicial',0,23],['endH','Hora final',0,23],['minute','Minuto',0,59]] as const).map(([key,label,min,max])=><Input key={key} label={label} type="number" min={min} max={max} value={window[key]} readOnly={!editable} onChange={e=>updateWindow(key,e.target.value)}/>) }<p className="text-xs text-dim sm:col-span-2">Horários: {text(value.horarios_especificos)||'Confira a janela de execução'}</p></div>:kind==='custom'?<Input label="Horários de execução" value={text(value.horarios_especificos)} readOnly={!editable} placeholder="09:00, 10:30, 13:00" onChange={e=>patch({horarios_especificos:e.target.value,scheduled_time:(parseCustomTimes(e.target.value)[0]||'06:00')+':00'})}/>:kind==='monthly_days_times'?<div className="space-y-3">{entries.map((entry,index)=><div key={index} className="grid sm:grid-cols-[100px_minmax(0,1fr)_auto] gap-2"><Input label={`Dia do mês ${index+1}`} type="number" min={1} max={28} value={entry.dia} readOnly={!editable} onChange={e=>{const next=entries.map((x,i)=>i===index?{...x,dia:Number(e.target.value)}:x);patch({dias_horarios_mes:storeEntries(next)})}}/><Input label={`Horários do dia ${index+1}`} value={entry.horariosRaw} readOnly={!editable} onChange={e=>{const next=entries.map((x,i)=>i===index?{...x,horariosRaw:e.target.value}:x);patch({dias_horarios_mes:JSON.stringify(next.map(x=>({dia:x.dia,horarios:x.horariosRaw.split(',').map(t=>t.trim())})))})}}/>{editable&&<Button type="button" variant="secondary" onClick={()=>patch({dias_horarios_mes:JSON.stringify(entries.filter((_,i)=>i!==index).map(x=>({dia:x.dia,horarios:x.horariosRaw.split(',').map(t=>t.trim())})))})}>Remover dia {index+1}</Button>}</div>)}{editable&&<Button type="button" variant="secondary" disabled={entries.length>=MAX_MONTH_DAYS} onClick={()=>{const day=Array.from({length:28},(_,i)=>i+1).find(d=>!entries.some(e=>e.dia===d));patch({dias_horarios_mes:storeEntries([...entries,{dia:day??1,horariosRaw:'06:00'}])})}}>Adicionar dia e horários</Button>}</div>:<Input label="Horário da agenda" type="time" value={text(value.scheduled_time).slice(0,5)} readOnly={!editable} onChange={e=>patch({scheduled_time:e.target.value+':00',schedule_hour:Number(e.target.value.slice(0,2)),schedule_minute:Number(e.target.value.slice(3,5))})}/>}
 {kind==='weekly'&&<Select label="Dia da semana" value={String(value.schedule_dow??1)} disabled={!editable} onChange={e=>patch({schedule_dow:Number(e.target.value)})}>{DOW_LABELS.map(([day,label])=><option key={day} value={day}>{label}</option>)}</Select>}
 {(kind==='monthly'||kind==='biweekly')&&<Input label={kind==='biweekly'?'Dia da primeira quinzena (1–13)':'Dia do mês (1–28)'} type="number" min={1} max={kind==='biweekly'?13:28} value={Number(value.schedule_dom??1)} readOnly={!editable} onChange={e=>patch({schedule_dom:Number(e.target.value)})}/>}
 {kind==='custom'&&<div className="flex flex-wrap gap-3">{DOW_LABELS.map(([day,label])=><label key={day} className="text-xs text-ink flex gap-1"><input type="checkbox" disabled={!editable} checked={text(value.dias_semana).split(',').includes(String(day))} onChange={e=>{const days=new Set(text(value.dias_semana).split(',').filter(Boolean));if(e.target.checked)days.add(String(day));else days.delete(String(day));patch({dias_semana:[...days].sort().join(',')||null})}}/>{label}</label>)}</div>}
 <label className="flex gap-2 text-sm text-ink"><input type="checkbox" disabled={!editable} checked={!!value.somente_dias_uteis} onChange={e=>patch({somente_dias_uteis:e.target.checked?1:0})}/>Somente dias úteis</label><Select label="Calendário de feriados" disabled={!editable} value={text(value.calendario_nome)} onChange={e=>patch({calendario_nome:e.target.value||null})}><option value="">Sem calendário adicional</option>{!!value.calendario_nome&&!calendars.data?.calendarios.some(c=>c.calendario_nome===value.calendario_nome)&&<option>{text(value.calendario_nome)}</option>}{calendars.data?.calendarios.map(c=><option key={c.calendario_nome}>{c.calendario_nome}</option>)}</Select>{calendars.isError&&<p role="alert" className="text-xs text-red-700 dark:text-red-400">Falha ao carregar calendários. <button type="button" className="underline" onClick={()=>calendars.refetch()}>Tentar novamente</button></p>}
 </>}</fieldset>
}
