import { useMemo, useRef, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Play, ScrollText } from 'lucide-react'
import { apiFetch, apiFetchBruto } from '../../lib/api'
import { publishedExecutionFlow } from '../../lib/workspaceNavigation'
import type { WorkspaceCapabilities, WorkspaceDefinition, WorkspaceLayout } from '../../lib/workspace'
import { useAuthStore } from '../../store/auth'
import { FluxoEditor } from '../etapas/FluxoEditor'
import { estiloEtapa, type PipelineExecucaoApi } from '../etapas/execucaoEtapas'
import { Button } from '../ui/Button'
import { Input, Select, Textarea } from '../ui/Input'
import { PageSpinner } from '../ui/Spinner'

type LogSelection = { task: string; attempt: number }
function TaskLog({name,runId,selection}:{name:string;runId:string;selection:LogSelection}) {
 const token = useAuthStore(s=>s.token)
 const log = useQuery({queryKey:['workspace-log',token,name,runId,selection.task,selection.attempt],queryFn:async({signal})=>(await apiFetchBruto(`/pipeline-task-log?${new URLSearchParams({pipeline_name:name,run_id:runId,task_id:selection.task,try_number:String(selection.attempt)})}`,{signal})).text(),retry:false})
 return <section className="min-w-0 border-t border-edge pt-4" aria-label="Log da tentativa"><h3 className="text-sm font-semibold text-ink mb-2">{selection.task} · tentativa {selection.attempt} · Airflow</h3>{log.isPending?<PageSpinner/>:log.isError?<p role="alert" className="text-sm text-red-700 dark:text-red-400">{log.error.message} <Button variant="secondary" size="sm" onClick={()=>log.refetch()}>Tentar novamente</Button></p>:<pre className="max-h-[480px] overflow-auto bg-canvas p-4 rounded-md text-xs text-ink whitespace-pre-wrap break-words">{log.data || 'Esta tentativa ainda não possui conteúdo de log.'}</pre>}</section>
}
function RunRequest({name,onRun,onClose}:{name:string;onRun:(id:string)=>void;onClose:()=>void}) {
 const [conf,setConf]=useState('{}');const [date,setDate]=useState('');const [error,setError]=useState('');const id=useRef(`workspace__${crypto.randomUUID()}`)
 const run=useMutation({mutationFn:async()=>{let parsed:unknown;try{parsed=JSON.parse(conf)}catch{throw new Error('Use um objeto JSON válido para os parâmetros da execução.')};if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('Os parâmetros da execução devem ser um objeto JSON.');return apiFetch<{runId:string;state:string}>(`/workspace/runs?${new URLSearchParams({name})}`,{method:'POST',body:JSON.stringify({conf:parsed,dag_run_id:id.current,...(date?{logical_date:date}:{})})})},onSuccess:next=>{onRun(next.runId);onClose()},onError:e=>setError(e.message)})
 return <section className="border border-edge bg-panel rounded-lg p-4 space-y-3" aria-label="Solicitar execução"><h2 className="font-semibold text-sm text-ink">Executar a configuração publicada</h2><p className="text-sm text-dim">O disparo cria uma corrida no Airflow. Uma DAG pausada continuará aguardando ativação; publicar e executar são ações separadas.</p><div className="grid gap-3 sm:grid-cols-2"><Textarea label="Parâmetros desta execução (JSON)" value={conf} onChange={e=>setConf(e.target.value)} rows={3}/><Input label="Data lógica (ISO 8601, opcional)" value={date} onChange={e=>setDate(e.target.value)} placeholder="2026-10-09T12:00:00Z"/></div>{error&&<p role="alert" className="text-sm text-red-700 dark:text-red-400">{error}</p>}<div className="flex gap-2"><Button loading={run.isPending} onClick={()=>run.mutate()}><Play size={14}/>Confirmar execução</Button><Button variant="secondary" disabled={run.isPending} onClick={onClose}>Fechar</Button></div></section>
}
export function WorkspaceOperations({name,date,runId,definition,layout,caps,logs,onDate,onRun}:{name:string;date:string;runId:string;definition:WorkspaceDefinition;layout:WorkspaceLayout;caps:WorkspaceCapabilities;logs:boolean;onDate:(date:string|null)=>void;onRun:(id:string|null)=>void}) {
 const token=useAuthStore(s=>s.token);const [requesting,setRequesting]=useState(false);const [search,setSearch]=useState('');const [selection,setSelection]=useState<LogSelection|null>(null)
 const query=useQuery({queryKey:['workspace-execution',token,name,date,runId],queryFn:({signal})=>apiFetch<PipelineExecucaoApi & {workspaceVersion?: {number:number;definition:WorkspaceDefinition;layout:WorkspaceLayout}}>(`/workspace/executions?${new URLSearchParams({name,...(date?{date}:{}),...(runId?{runId}:{})})}`,{signal}),retry:false,refetchInterval:30_000})
 const version=query.data?.workspaceVersion
 const flow=useMemo(()=>publishedExecutionFlow(version?.definition??definition,version?.layout??layout),[version,definition,layout])
 const resolved=query.data?.identidade?.dag_run_id??query.data?.identidade?.run_id??''
 return <div className="space-y-4"><p className="text-xs text-dim">{version?`Definição da corrida · versão ${version.number}`:'Definição publicada atual · corrida sem versão histórica vinculada'}</p><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-dim">{logs?'Etapas e tentativas da corrida selecionada. O conteúdo do log é carregado ao abrir uma etapa.':'Selecione uma etapa para investigar, reprocessar ou gerenciar uma pausa.'}</p>{caps.actions.execute&&<Button size="sm" onClick={()=>setRequesting(true)}><Play size={14}/>Executar pipeline</Button>}</div>{requesting&&<RunRequest name={name} onRun={id=>onRun(id)} onClose={()=>setRequesting(false)}/>}
  {!logs?<div className="h-[760px] sm:h-[700px] min-w-0"><FluxoEditor pipeline={name} readOnly modoExecucao dataExecucao={date||null} onDataExecucao={onDate} workspace={{flow,runId:runId||null,onRun,canReprocess:!!caps.actions.reprocess,canPause:!!caps.actions.pauseStages}}/></div>:<section className="bg-panel border border-edge rounded-lg p-4 space-y-4"><div className="flex flex-wrap gap-3"><Input label="Buscar etapa nesta corrida" value={search} onChange={e=>setSearch(e.target.value)} className="sm:max-w-xs"/><Input label="Data operacional" type="date" value={date} onChange={e=>onDate(e.target.value||null)}/>{query.data?.identidade?.candidatos?.length?<Select label="Corrida" value={runId||resolved} onChange={e=>{setSelection(null);onRun(e.target.value)}} className="min-w-0 sm:max-w-md">{query.data.identidade.candidatos.map(row=><option key={row.run_id} value={row.run_id??''}>{row.run_id} · {row.status}</option>)}</Select>:null}</div><p className="text-xs text-dim break-all">Corrida: {resolved||'Nenhuma corrida identificada'} · {query.data?.data_referencia??date}</p>{query.isPending?<PageSpinner/>:query.isError?<p role="alert" className="text-sm text-red-700 dark:text-red-400">{query.error.message}</p>:<><div className="divide-y divide-edge">{query.data.etapas.filter(step=>step.job_name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(step=><div key={step.job_name} className="flex flex-wrap items-center gap-3 py-3"><span className="text-sm text-ink min-w-0 break-words basis-full sm:basis-auto sm:flex-1">{step.job_name}</span><span className="text-xs text-dim">{step.sem_execucao?'Sem execução':estiloEtapa(step.status)?.rotulo??'Não informado'}</span><div className="flex flex-wrap gap-2">{[...step.tentativas.map(t=>t.attempt),step.attempt??1].filter((v,i,a):v is number=>v!==null&&a.indexOf(v)===i).map(attempt=><Button key={attempt} variant="secondary" size="sm" disabled={!resolved||!step.task_id} onClick={()=>setSelection({task:step.task_id!,attempt})}><ScrollText size={14}/>Tentativa {attempt}</Button>)}</div></div>)}{!query.data.etapas.some(step=>step.job_name.toLocaleLowerCase().includes(search.toLocaleLowerCase()))&&<p className="text-sm text-dim py-4">Nenhuma etapa encontrada nesta corrida para a busca.</p>}</div>{selection&&resolved&&<TaskLog key={`${name}:${resolved}:${selection.task}:${selection.attempt}`} name={name} runId={resolved} selection={selection}/>}</>}</section>}
 </div>
}
