import { WorkspaceCatalogFields, WorkspaceScheduleFields } from './WorkspacePipelineFields'
import { useState } from 'react'
import { object, pipelineMetadata, text, type WorkspaceDefinition } from '../../lib/workspace'
import { Button } from '../ui/Button'
import { Textarea } from '../ui/Input'

export function WorkspaceDraftTools({definition,editable,onApply}:{definition:WorkspaceDefinition;editable:boolean;onApply:(next:WorkspaceDefinition)=>void}) {
 const [mode,setMode]=useState<'metadata'|'import'|null>(null);const [value,setValue]=useState('');const [error,setError]=useState('')
 function open(next:'metadata'|'import'){setMode(next);setError('');setValue(next==='metadata'?JSON.stringify(definition.metadata??{},null,2):'[\n  {"job_name":"nova_etapa","job_type":"shell","job_command":"true","execution_order":1}\n]')}
 function apply(){try{
  const raw:unknown=JSON.parse(value)
  if(mode==='metadata') {if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Use um objeto JSON para a configuração do pipeline.');onApply({...definition,metadata:object(raw)})}
  else {
   if(!Array.isArray(raw)||!raw.length||raw.length+definition.nodes.length>500)throw new Error('Informe uma lista com até 500 etapas no total.')
   const names=new Set(definition.nodes.map(n=>n.id.toLocaleLowerCase()));const nodes=raw.map(item=>{const row=object(item);const name=text(row.job_name);if(!/^[A-Za-z0-9_.-]+$/.test(name)||name.length>200||names.has(name.toLocaleLowerCase()))throw new Error('Cada etapa exige um identificador único, sem espaços.');names.add(name.toLocaleLowerCase());if(!text(row.job_type))throw new Error('Informe job_type em cada etapa.');if(row.depends_on_jobs||row.condition_json)throw new Error('Importe primeiro as etapas sem dependências/decisões e monte as conexões no canvas. Esses campos não são descartados silenciosamente.');return {id:name,type:text(row.job_type),configuration:{legacyJob:{...row,pipeline_name:definition.identity.pipelineName},etl_pipeline_job_param:[]}}})
   onApply({...definition,nodes:[...definition.nodes,...nodes]})
  };setMode(null)
 }catch(e){setError(e instanceof Error?e.message:'Configuração inválida.')}}
 return <details className="border-b border-edge pb-3"><summary className="cursor-pointer text-sm font-medium text-ink focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-600">Configuração do pipeline · {text(pipelineMetadata(definition).project_name)||'Projeto não informado'}</summary><div className="mt-3 space-y-3"><p className="text-xs text-dim">Agenda, política sem movimento, parâmetros e vínculos ficam no rascunho. A configuração completa usa JSON; referências protegidas devem ser preservadas. Publicar exige a validação desta revisão.</p><div className="grid sm:grid-cols-2 gap-3"><WorkspaceCatalogFields project={text(pipelineMetadata(definition).project_name)} domain={text(pipelineMetadata(definition).domain)} editable={editable} onChange={(field,value)=>onApply({...definition,metadata:{...object(definition.metadata),legacyPipeline:{...pipelineMetadata(definition),[field]:value}}})}/></div><WorkspaceScheduleFields value={pipelineMetadata(definition)} editable={editable} onChange={next=>onApply({...definition,metadata:{...object(definition.metadata),legacyPipeline:next}})}/><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={()=>open('metadata')}>Configuração completa (JSON)</Button>{editable&&<Button size="sm" variant="secondary" onClick={()=>open('import')}>Importar etapas em lote</Button>}</div>{mode&&<div className="space-y-3"><Textarea label={mode==='metadata'?'Metadados e catálogos do pipeline':'Etapas a importar (lista JSON)'} value={value} readOnly={!editable} onChange={e=>setValue(e.target.value)} rows={12} error={error} className="font-mono text-xs"/><div className="flex gap-2">{editable&&<Button size="sm" onClick={apply}>{mode==='import'?'Adicionar ao rascunho':'Aplicar ao rascunho'}</Button>}<Button size="sm" variant="secondary" onClick={()=>setMode(null)}>Fechar</Button></div></div>}<p className="text-xs text-dim">{definition.nodes.length} etapas na revisão atual.</p></div></details>
}
