import type { Node } from '@xyflow/react'
import type { EtapaExecucaoApi } from '../etapas/execucaoEtapas'
import { encryptedParameter, object, text } from '../../lib/workspace'
import { typeLabel } from './workspaceCatalog'
export function WorkspaceRunProperties({node,step,pipeline,runId}:{node:Node;step:EtapaExecucaoApi|undefined;pipeline:string;runId:string|null}) {
 const kind=text(node.data.type)||(node.type==='etapa'?'datastage':node.type??'')
 const params=Array.isArray(node.data.params)?node.data.params.map(object):[]
 const search=new URLSearchParams(window.location.search);if(runId)search.set('run_id',runId);search.set('etapa',node.id);search.set('experiencia','sustentacao')
 return <section className="p-4 space-y-5" aria-label="Investigação da etapa"><div><h2 className="text-sm font-semibold text-ink break-words">{node.id}</h2><p className="text-xs text-dim mt-1">{typeLabel(kind)}</p></div><dl className="grid grid-cols-2 gap-4 text-xs"><div><dt className="text-dim">Início</dt><dd className="text-ink mt-1 break-words">{step?.inicio??'Não informado'}</dd></div><div><dt className="text-dim">Duração</dt><dd className="text-ink mt-1">{step?.duration_seconds!=null?`${step.duration_seconds}s`:'Não informada'}</dd></div><div><dt className="text-dim">Tentativa</dt><dd className="text-ink mt-1">{step?.attempt??'Não informada'}</dd></div><div><dt className="text-dim">Origem do estado</dt><dd className="text-ink mt-1">Telemetria da etapa</dd></div></dl><div className="border-t border-edge pt-4"><h3 className="text-xs font-semibold text-ink mb-3">Parâmetros</h3>{params.length?<dl className="space-y-3 text-xs">{params.map((param,index)=><div key={index}><dt className="text-dim break-words">{text(param.param_name)||text(param.name)}</dt><dd className="text-ink break-words mt-1">{encryptedParameter(param)?'Valor protegido na origem':text(param.param_value)||text(param.value)||'Não informado'}</dd></div>)}</dl>:<p className="text-xs text-dim">Nenhum parâmetro disponível nesta definição.</p>}</div><div className="border-t border-edge pt-4"><h3 className="text-xs font-semibold text-ink mb-2">Investigação</h3>{runId?<a className="inline-flex rounded border border-edge px-3 py-2 text-sm text-blue-700 dark:text-blue-400 hover:bg-edge/20" href={`/pipelines/${encodeURIComponent(pipeline)}/logs?${search}`}>Abrir logs desta etapa</a>:<p className="text-xs text-dim">Selecione uma corrida para abrir os logs.</p>}</div></section>
}
