const fs=require('fs'),assert=require('assert/strict'),path=require('path');
const root=path.resolve(__dirname,'../..');const {transform}=require(root+'/ui-react/node_modules/sucrase');
function load(file,req=require){const m={exports:{}};new Function('require','module','exports',transform(fs.readFileSync(root+'/ui-react/src/lib/'+file,'utf8'),{transforms:['typescript','imports']}).code)(req,m,m.exports);return m.exports}
const w=load('workspace.ts');const n=load('workspaceNavigation.ts',()=>w);
const name='ação/A %25';const search=new URLSearchParams({pipeline:name,modo:'execucao',data:'2026-10-09',run_id:'manual__a/b%',de:'malha:Origem & B'});
const url=new URL(n.legacyWorkspacePath('fluxos',search),'http://local');assert.equal(decodeURIComponent(url.pathname.split('/')[2]),name);assert.equal(url.searchParams.get('run_id'),'manual__a/b%');assert.equal(url.searchParams.get('de'),'malha:Origem & B');assert.equal(url.searchParams.get('experiencia'),'sustentacao');assert(url.pathname.endsWith('/execucoes'));
const tab=new URL(n.contextualPath(name,'logs',url.searchParams),'http://local');assert.equal(tab.searchParams.get('data'),'2026-10-09');assert.equal(tab.searchParams.get('run_id'),'manual__a/b%');assert.equal(n.legacyWorkspacePath('jobs',new URLSearchParams({pipeline:name,legado:'1'})),null);
const flow={schemaVersion:1,identity:{pipelineName:name},nodes:[{id:'old',type:'shell',configuration:{legacyJob:{job_name:'old',job_command:'literal old'},etl_pipeline_job_param:[]}},{id:'decision',type:'decisao',configuration:{legacyJob:{condition_json:JSON.stringify({ramo_verdadeiro:['old'],casos:[{ramo:['old']}],job_name:'old',source_job:'old',child_job:'old',literal:'old'})}}}],edges:[{source:'decision',target:'old',branch:'sim'}]};const layout={schemaVersion:1,nodes:{old:{x:1,y:2}}};const original=structuredClone(flow);const renamed=w.renameWorkspaceNode(flow,layout,'old','new');assert.equal(renamed.definition.nodes[0].id,'new');assert.equal(renamed.definition.nodes[0].configuration.legacyJob.job_command,'literal old');assert.equal(renamed.definition.edges[0].target,'new');const condition=JSON.parse(renamed.definition.nodes[1].configuration.legacyJob.condition_json);assert.deepEqual(condition.ramo_verdadeiro,['new']);assert.equal(condition.literal,'old');assert.equal(condition.job_name,'new');assert.equal(condition.source_job,'new');assert.equal(condition.child_job,'old');assert.deepEqual(renamed.layout.nodes.new,{x:1,y:2});assert.deepEqual(flow,original);
flow.nodes[0].configuration.etl_pipeline_job_param=[{param_type:'Encrypted',secretReference:{jobName:'old'}}];assert.throws(()=>w.renameWorkspaceNode(flow,layout,'old','new'),/protegidos/);
const snapshot=n.publishedExecutionFlow(original,layout);assert.equal(snapshot.nodes[0].job_name,'old');assert.equal(snapshot.nodes[0].layout_x,1);assert.equal(snapshot.nodes[1].condition.ramo_verdadeiro[0],'old');console.log('Workspace F5 navigation/draft/snapshot PASS');
