const fs=require('fs'),assert=require('assert/strict'),path=require('path');
const root=path.resolve(__dirname,'../..');const {transform}=require(root+'/ui-react/node_modules/sucrase');
function load(file,req=require){const m={exports:{}};new Function('require','module','exports',transform(fs.readFileSync(root+'/ui-react/src/lib/'+file,'utf8'),{transforms:['typescript','imports']}).code)(req,m,m.exports);return m.exports}
const {arrangeWorkspace}=load('workspaceLayout.ts');
const definition={nodes:['start','left','right','join','tail'].map(id=>({id})),edges:[{source:'start',target:'left'},{source:'start',target:'right'},{source:'left',target:'join'},{source:'right',target:'join'},{source:'join',target:'tail'}]};const layout={schemaVersion:1,nodes:{left:{x:17,y:22,extra:'keep'}},extra:true};const original=structuredClone(layout);const graph=structuredClone(definition);const next=arrangeWorkspace(definition,layout);assert.equal(next.nodes.left.x,next.nodes.right.x);assert.notEqual(next.nodes.left.y,next.nodes.right.y);assert(next.nodes.join.x>next.nodes.left.x);assert(next.nodes.tail.x>next.nodes.join.x);assert.equal(next.nodes.left.extra,'keep');assert.deepEqual(layout,original);assert.deepEqual(definition,graph);assert.equal(Object.keys(next.nodes).length,5);
const cycle=arrangeWorkspace({nodes:[{id:'a'},{id:'b'}],edges:[{source:'a',target:'b'},{source:'b',target:'a'}]}, {schemaVersion:1,nodes:{}});assert.equal(Object.keys(cycle.nodes).length,2);assert(Object.values(cycle.nodes).every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));console.log('Workspace reference branched layout and immutable input PASS');
const w=load('workspace.ts');const decision=load('workspaceDecision.ts',name=>name==='./workspace'?w:require(name));const nav=load('workspaceNavigation.ts',()=>w);
for(const handle of ['sim','nao','caso:positivo','senao']){
 const condition=handle.startsWith('caso:')||handle==='senao'?{tipo:'switch',literal:'preserve',casos:[{nome:'positivo',ramo:[]}],ramo_senao:[]}:{tipo:'sql',literal:'preserve',ramo_verdadeiro:[],ramo_falso:[]};const d={schemaVersion:1,identity:{pipelineName:'test'},nodes:[{id:'D',type:'decisao',configuration:{legacyJob:{condition_json:JSON.stringify(condition)}}},{id:'A',type:'sql',configuration:{legacyJob:{}}}],edges:[]};const before=structuredClone(d);const connected=decision.connectWorkspaceDecision(d,'D','A',handle);assert.deepEqual(d,before);assert.equal(connected.edges[0].branch,handle);assert.equal(decision.decisionEdgeHandle(connected.nodes[0],connected.edges[0]),handle);const roundtrip=nav.publishedExecutionFlow(connected,{schemaVersion:1,nodes:{}});assert.equal(roundtrip.nodes[0].condition.literal,'preserve');assert(JSON.stringify(roundtrip.nodes[0].condition).includes('A'));const removed=decision.removeWorkspaceEdges(connected,new Set(['0']));assert.equal(removed.edges.length,0);assert(!JSON.stringify(decision.decisionCondition(removed.nodes[0])).includes('A'));assert.equal(decision.connectWorkspaceDecision(connected,'D','A',handle),connected);assert.throws(()=>decision.connectWorkspaceDecision(d,'D','A','inexistente'),/saída/);
}
const sw={id:'D',type:'decisao',configuration:{legacyJob:{condition_json:JSON.stringify({casos:[{nome:'x',ramo:['A']}],ramo_senao:['B']})}}};assert.deepEqual(decision.decisionHandles(sw),['caso:x','senao']);assert.equal(decision.decisionEdgeHandle(sw,{source:'D',target:'A'}),'caso:x');assert.equal(decision.decisionEdgeHandle(sw,{source:'D',target:'B'}),'senao');console.log('Workspace decision branch creation/removal/switch/roundtrip PASS');

const tall=arrangeWorkspace(definition,layout,170);assert.equal(Math.abs(tall.nodes.left.y-tall.nodes.right.y),170);assert.deepEqual(layout,original);
