const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..');const {transform}=require(root+'/ui-react/node_modules/sucrase');
function load(file,requireFn=require){const m={exports:{}};new Function('require','module','exports',transform(fs.readFileSync(root+'/ui-react/src/lib/'+file,'utf8'),{transforms:['typescript','imports']}).code)(requireFn,m,m.exports);return m.exports}
const w=load('workspace.ts');
const types=['datastage','sql','python','shell','storedproc','http','decisao','aguarde','notificacao','email','valida_arquivo'];
const names=['Operação A/B %25','Espaços & ? # ç','ação_東京'];
for(const name of names){assert.equal(decodeURIComponent(w.workspacePath(name).split('/')[2]),name);assert.equal(w.initialWorkspace(name,'Nome humano','','','').definition.identity.pipelineName,name)}
const d={schemaVersion:1,identity:{pipelineName:names[0],unknown:null},metadata:{legacyTables:{etl_pipeline_param:[{param_name:'normal',param_value:'v',extra:3},{param_name:'cifrado',param_type:'Encrypted',param_value:'***',secretReference:{id:2}}],unknownTable:[{a:null}]}},nodes:types.map((type,i)=>({id:'n'+i,type,extension:{keep:null},configuration:{legacyJob:{job_command:'antigo',special:[null,{foo:'bar'}]},unknownConfig:{nested:[1,2]},etl_pipeline_job_param:[{param_name:'secret',secretReference:{id:i},param_value:'***'}]}})),edges:[{source:'n0',target:'n1',branch:'sucesso',unknown:9}],unknownTop:{z:null}};
const original=structuredClone(d);const node=w.patchLegacy(d.nodes[0],'job_command','novo');assert.equal(node.configuration.legacyJob.job_command,'novo');assert.deepEqual(node.configuration.unknownConfig,d.nodes[0].configuration.unknownConfig);assert.deepEqual(node.configuration.legacyJob.special,d.nodes[0].configuration.legacyJob.special);assert.deepEqual(d,original);
const layout={schemaVersion:1,nodes:{n0:{x:1,y:2,zoom:7},n1:{x:3,y:4}},custom:null};
const changed=w.setPipelineParameters(d,w.pipelineParameters(d).map((p,i)=>i? p:{...p,param_value:'editado'}));assert.deepEqual(changed.metadata.legacyTables.unknownTable,d.metadata.legacyTables.unknownTable);assert.deepEqual(changed.metadata.legacyTables.etl_pipeline_param[1],d.metadata.legacyTables.etl_pipeline_param[1]);assert(w.encryptedParameter(w.pipelineParameters(d)[1]));
assert.throws(()=>w.connectWorkspace(d,'n1','n0'),/ciclo/);assert.equal(w.connectWorkspace(d,'n0','n1'),d);const connected=w.connectWorkspace(d,'n1','n2');assert.deepEqual(connected.edges[0],d.edges[0]);assert.deepEqual(connected.nodes,d.nodes);
const removed=w.removeWorkspaceNode(d,layout,'n0');assert.equal(removed.definition.edges.length,0);assert.deepEqual(removed.layout.nodes.n1,layout.nodes.n1);assert.equal(removed.layout.custom,null);assert.deepEqual(d,original);
const calls=[];const fake={apiFetch:async(p,o={})=>{calls.push({p,...o});return{}},apiFetchBruto:async(p,o={})=>{calls.push({p,...o});return{status:204}}};const api=load('workspaceApi.ts',()=>fake).workspaceApi;
(async()=>{const draft={draftId:'00000000-0000-0000-0000-000000000001',revision:7};await api.context(names[0]);await api.import(names[0]);await api.create(d,layout);await api.save(draft,d,layout,19);await api.lease(draft.draftId);await api.transfer(draft,19);await api.release(draft,19);await api.discard(draft,19);assert.equal(new URL(calls[0].p,'http://local').searchParams.get('name'),names[0]);assert(calls.every(c=>c.p.startsWith('/workspace/')));const payload=JSON.parse(calls.find(c=>c.method==='PUT').body);assert.deepEqual(payload,{expectedRevision:7,fence:19,definition:d,layout});console.log(JSON.stringify({typesPreserved:11,exactIdentities:3,transportCalls:calls.length,passed:true}))})().catch(e=>{console.error(e);process.exit(1)})
