import { WorkspaceCatalogFields, WorkspaceScheduleFields } from '../components/workspace/WorkspacePipelineFields'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useMutation } from '@tanstack/react-query'
import { ArrowRight, FilePlus2 } from 'lucide-react'
import { Input, Textarea } from '../components/ui/Input'
import { Button } from '../components/ui/Button'
import { PageSpinner } from '../components/ui/Spinner'
import { useWorkspaceCapabilities } from '../components/workspace/useWorkspaceCapabilities'
import { initialWorkspace, technicalSuggestion, workspacePath } from '../lib/workspace'
import { workspaceApi } from '../lib/workspaceApi'
import { useAuthStore } from '../store/auth'
export default function PipelineCreate(){
 const capabilities=useWorkspaceCapabilities();const navigate=useNavigate();const user=useAuthStore(s=>s.user)
 const [name,setName]=useState('');const [identifier,setIdentifier]=useState('');const [custom,setCustom]=useState(false);const [project,setProject]=useState('');const [domain,setDomain]=useState('');const [description,setDescription]=useState('');const [error,setError]=useState('')
 const [schedule,setSchedule]=useState<Record<string,unknown>>({schedule_type:'on_demand'})
 const technical=custom?identifier:technicalSuggestion(name)
 const create=useMutation({mutationFn:()=>{if(!name.trim()||!technical.trim()||technical.length>200)throw new Error('Informe o nome e um identificador de até 200 caracteres');const flow=initialWorkspace(technical,name.trim(),project,domain,description);flow.definition.metadata={legacyPipeline:{...flow.definition.metadata?.legacyPipeline as Record<string,unknown>,...schedule}};return workspaceApi.create(flow.definition,flow.layout)},onSuccess:draft=>navigate(workspacePath(draft.pipelineName,'fluxo','desenvolvimento')),onError:err=>setError(err.message)})
 if(capabilities.isPending)return <PageSpinner/>
 if(!capabilities.data?.enabled||!capabilities.data.actions.editDraft)return <section className="space-y-4"><h1 className="text-xl font-semibold text-ink">Criação de rascunho indisponível</h1><p className="text-sm text-dim">{capabilities.isError?'Não foi possível consultar o workspace. A lista de pipelines continua disponível.':'Sua sessão não tem a capacidade de criar rascunhos neste ambiente.'}</p><Link to="/pipelines" className="text-blue-700 dark:text-blue-400 underline">Voltar aos pipelines</Link></section>
 return <div className="space-y-6"><nav aria-label="Caminho" className="text-sm text-dim"><Link to="/pipelines" className="hover:underline">Pipelines</Link><span className="mx-2">/</span>Criar pipeline</nav><header><h1 className="text-2xl font-semibold text-ink">Criar pipeline</h1><p className="text-sm text-dim mt-2">Comece pelo essencial. Configure as etapas no espaço de trabalho.</p></header>
  <form onSubmit={e=>{e.preventDefault();setError('');create.mutate()}} className="grid lg:grid-cols-[minmax(0,1fr)_320px] gap-6"><section className="bg-panel border border-edge rounded-lg p-5 space-y-5"><h2 className="text-base font-semibold text-ink">Identificação</h2><div className="grid sm:grid-cols-2 gap-5"><Input label="Nome para exibição" required maxLength={200} value={name} onChange={e=>setName(e.target.value)} ajuda="Um nome fácil de reconhecer na operação."/><Input label="Identificador técnico" required maxLength={200} value={technical} onChange={e=>{setCustom(true);setIdentifier(e.target.value)}} ajuda="Preservado exatamente como informado; não pode ser renomeado depois."/><WorkspaceCatalogFields project={project} domain={domain} editable={!create.isPending} onChange={(field,value)=>field==='project_name'?setProject(value):setDomain(value)}/></div><Textarea label="Descrição" rows={4} maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)}/><WorkspaceScheduleFields value={schedule} editable={!create.isPending} onChange={setSchedule}/><div className="border-t border-edge pt-5"><h3 className="font-medium text-sm text-ink">Fluxo em branco</h3><p className="text-sm text-dim mt-2">Você adicionará e conectará as etapas após criar o rascunho.</p></div>{error&&<p role="alert" className="text-sm text-red-700 dark:text-red-400">{error}</p>}<div className="flex flex-wrap justify-end gap-3 pt-2"><Link to="/pipelines" className="text-sm text-dim px-3 py-2 hover:underline">Cancelar</Link><Button type="submit" loading={create.isPending}>Criar e abrir fluxo<ArrowRight size={16}/></Button></div></section><aside className="bg-panel border border-edge rounded-lg p-5 self-start"><FilePlus2 size={28} className="text-blue-700 dark:text-blue-400 mb-5"/><h2 className="text-base font-semibold text-ink break-words">{name||'Seu novo pipeline'}</h2><p className="font-mono text-xs text-dim mt-2 break-all">{technical||'identificador_do_pipeline'}</p><dl className="text-sm mt-6 space-y-3"><div className="flex gap-3 justify-between"><dt className="text-dim">Responsável</dt><dd className="text-ink">{user?.matricula}</dd></div><div className="flex gap-3 justify-between"><dt className="text-dim">Estado inicial</dt><dd className="text-ink">Rascunho</dd></div></dl><p className="text-sm text-dim mt-6 border-t border-edge pt-5">A criação salva um rascunho. A configuração publicada e o agendamento permanecem separados.</p></aside></form></div>
}
