import { Link, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { GitBranch, FilePlus2 } from 'lucide-react'
import { apiFetch } from '../lib/api'
import { workspaceApi } from '../lib/workspaceApi'
import { definitionLabel, object, pipelineMetadata, text, workspacePath, type WorkspaceDraft, type WorkspaceExperience } from '../lib/workspace'
import { useWorkspaceCapabilities } from '../components/workspace/useWorkspaceCapabilities'
import { WorkspaceEditor } from '../components/workspace/WorkspaceEditor'
import { Button } from '../components/ui/Button'
import { Select, Input } from '../components/ui/Input'
import { PageSpinner } from '../components/ui/Spinner'
import { toast } from '../components/ui/Toast'
import { useAuthStore } from '../store/auth'
import { estiloEtapa, type PipelineExecucaoApi } from '../components/etapas/execucaoEtapas'
function ExecutionContext({name,date,logs}:{name:string;date:string;logs:boolean}){
 const token=useAuthStore(s=>s.token)
 const query=useQuery({queryKey:['workspace-execution',token,name,date],queryFn:({signal})=>apiFetch<PipelineExecucaoApi>(`/workspace/executions?${new URLSearchParams({name,...(date?{date}:{})})}`,{signal}),retry:false,refetchInterval:30_000})
 if(query.isPending)return <PageSpinner/>
 if(query.isError)return <p role="alert" className="text-sm text-red-700 dark:text-red-400">{query.error.message}</p>
 const data=query.data
 return <section className="bg-panel border border-edge rounded-lg p-5"><div className="flex flex-wrap justify-between gap-3 mb-5"><h2 className="font-semibold text-ink">Execução · {data.data_referencia??'data operacional corrente'}</h2>{logs&&<Link to={`/logs?${new URLSearchParams({pipeline:name,...(date?{date}:{})})}`} className="text-sm text-blue-700 dark:text-blue-400 underline">Abrir logs deste pipeline</Link>}</div>{data.corrida?<p className="text-sm text-dim mb-4">Estado: {estiloEtapa(data.corrida.status)?.rotulo??'Não informado'}</p>:<p className="text-sm text-dim mb-4">Nenhuma execução encontrada para esta data.</p>}{data.identidade?.degradado&&<p className="text-sm text-amber-800 dark:text-amber-300 mb-4">{data.identidade.motivo||'Dados de execução parciais.'}</p>}<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="text-dim"><tr><th className="py-2 pr-4">Etapa</th><th className="py-2 pr-4">Estado</th><th className="py-2 pr-4">Início</th><th className="py-2">Duração</th></tr></thead><tbody>{data.etapas.map((step,index)=><tr key={`${step.job_name}-${index}`} className="border-t border-edge"><td className="py-3 pr-4 text-ink">{step.job_name}</td><td className="pr-4 text-ink">{step.sem_execucao?'Sem execução':estiloEtapa(step.status)?.rotulo??'Não informado'}</td><td className="pr-4 text-dim whitespace-nowrap">{step.inicio??'—'}</td><td className="text-dim tabular-nums">{step.duration_seconds===null?'—':`${step.duration_seconds} s`}</td></tr>)}</tbody></table></div></section>
}
export default function PipelineWorkspace(){
 const {nome=''}=useParams();const [search,setSearch]=useSearchParams();const location=useLocation();const navigate=useNavigate();const client=useQueryClient();const token=useAuthStore(s=>s.token)
 const caps=useWorkspaceCapabilities();const requested=search.get('experiencia');const experience:WorkspaceExperience=requested==='desenvolvimento'||requested==='sustentacao'?requested:'consulta'
 const tab=location.pathname.split('/').filter(Boolean).at(-1)??'visao-geral';const date=search.get('data')??''
 const context=useQuery({queryKey:['workspace-context',token,nome],queryFn:({signal})=>workspaceApi.context(nome,signal),enabled:!!nome&&caps.data?.enabled===true&&caps.data.actions.consultDefinition,retry:false,refetchInterval:30_000})
 const importing=useMutation({mutationFn:()=>workspaceApi.import(nome),onSuccess:()=>{client.invalidateQueries({queryKey:['workspace-context',token,nome]});navigate(workspacePath(nome,'fluxo','desenvolvimento'))},onError:error=>toast.error(error.message)})
 const data=context.data;const development=experience==='desenvolvimento';const draft=development||search.get('fonte')==='rascunho'||!data?.published?data?.draft??null:null;const flow=draft?{definition:draft.definition,layout:draft.layout,readOnlyReasons:draft.readOnlyReasons}:data?.published
 const tabs=[['visao-geral','Visão geral'],...(caps.data?.actions.consultStages?[['fluxo','Fluxo'],['etapas','Etapas'],['parametros','Parâmetros']]:[]),...(caps.data?.actions.consultStages&&caps.data.actions.consultLogs?[['execucoes','Execuções']]:[])]
 function saved(next:WorkspaceDraft){client.setQueryData(['workspace-context',token,nome],data?{...data,draft:next}:undefined)}
 if(caps.isPending||context.isPending&&context.fetchStatus!=='idle')return <PageSpinner/>
 if(caps.isError||!caps.data?.enabled||!caps.data.actions.consultDefinition||context.isError)return <div className="space-y-4"><h1 className="text-xl font-semibold text-ink">Workspace indisponível</h1><p role="alert" className="text-sm text-dim">{context.error?.message??'Não foi possível consultar o workspace nesta sessão. A lista de pipelines continua disponível.'}</p><Link className="text-sm text-blue-700 dark:text-blue-400 underline" to="/pipelines">Voltar aos pipelines</Link></div>
 if(!data)return <PageSpinner/>
 const title=flow?definitionLabel(flow.definition):data.pipelineName;const metadata=flow?pipelineMetadata(flow.definition):object(data.summary);const viewingTab=tabs.some(t=>t[0]===tab)?tab:experience==='sustentacao'&&caps.data.actions.consultStages&&caps.data.actions.consultLogs?'execucoes':'visao-geral'
 return <div className="space-y-5"><nav aria-label="Caminho" className="text-sm text-dim"><Link to="/pipelines" className="hover:underline">Pipelines</Link><span className="mx-2">/</span>{title}</nav><header className="flex flex-wrap justify-between items-start gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold text-ink break-words">{title}</h1><span className="px-2 py-1 rounded-md text-xs border border-edge text-ink bg-panel">{data.environmentLabel??'Workspace'}</span><span className="text-xs text-dim">{draft?`Rascunho · revisão ${draft.revision}`:data.published?'Configuração publicada':'Rascunho'}</span></div><p className="font-mono text-xs text-dim mt-2 break-all">{data.pipelineName}</p></div><Select label="Experiência" value={experience} onChange={e=>navigate(workspacePath(nome,e.target.value==='sustentacao'?'execucoes':e.target.value==='desenvolvimento'?'fluxo':'visao-geral',e.target.value as WorkspaceExperience)+(date?`&data=${encodeURIComponent(date)}`:'')+(draft?'&fonte=rascunho':''))} className="min-w-44"><option value="consulta">Consulta</option><option value="desenvolvimento">Desenvolvimento</option><option value="sustentacao">Sustentação</option></Select></header>
  <nav aria-label="Abas do pipeline" className="flex gap-1 border-b border-edge overflow-x-auto">{tabs.map(([id,label])=><Link key={id} to={`${workspacePath(nome,id,experience)}${date?`&data=${encodeURIComponent(date)}`:''}${draft?'&fonte=rascunho':''}`} aria-current={viewingTab===id?'page':undefined} className={`px-4 py-3 text-sm whitespace-nowrap border-b-2 ${viewingTab===id?'border-blue-600 text-blue-700 dark:text-blue-400 font-semibold':'border-transparent text-dim hover:text-ink'}`}>{label}</Link>)}</nav>
  {data.published&&data.draft&&<Select label="Definição" value={draft?'rascunho':'publicado'} onChange={e=>{const next=new URLSearchParams(search);next.set('fonte',e.target.value);if(e.target.value==='publicado'&&development)next.set('experiencia','consulta');setSearch(next)}} className="max-w-xs"><option value="publicado">Configuração publicada</option><option value="rascunho">Rascunho · revisão {data.draft.revision}</option></Select>}
  {development&&!data.draft&&caps.data.actions.editDraft&&data.published&&<div className="flex flex-wrap items-center justify-between gap-3 bg-panel border border-edge rounded-lg p-4"><p className="text-sm text-dim">Crie um rascunho a partir da configuração publicada para iniciar a montagem.</p><Button onClick={()=>importing.mutate()} loading={importing.isPending}><FilePlus2 size={16}/>Criar rascunho desta configuração</Button></div>}
  {viewingTab==='visao-geral'?<section className="bg-panel border border-edge rounded-lg p-5 space-y-5"><h2 className="font-semibold text-ink">Visão geral</h2><p className="text-sm text-dim whitespace-pre-wrap">{text(metadata.descricao)||'Descrição não informada.'}</p><dl className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5 text-sm">{[['Projeto',text(metadata.project_name)||'Não informado'],['Domínio',text(metadata.domain)||'Não informado'],['Responsável',draft?.responsible||text(object(data.summary).responsible)||'Não informado'],['Estado',draft?'Rascunho':data.published?'Publicado':'Rascunho']].map(([label,value])=><div key={label}><dt className="text-dim mb-1">{label}</dt><dd className="text-ink break-words">{value}</dd></div>)}</dl>{caps.data.actions.consultStages&&<Link to={`${workspacePath(nome,'fluxo',experience)}${date?`&data=${encodeURIComponent(date)}`:''}${draft?'&fonte=rascunho':''}`} className="inline-flex items-center gap-2 text-sm text-blue-700 dark:text-blue-400 underline"><GitBranch size={16}/>Abrir fluxo</Link>}{!caps.data.actions.consultStages&&<p className="text-sm text-dim">A consulta de etapas não está autorizada nesta sessão.</p>}</section>:viewingTab==='execucoes'?<><div className="max-w-xs"><Input label="Data operacional" type="date" value={date} onChange={e=>{const next=new URLSearchParams(search);if(e.target.value)next.set('data',e.target.value);else next.delete('data');setSearch(next)}}/></div>{data.published?<ExecutionContext name={nome} date={date} logs={caps.data.actions.consultLogs}/>:<p className="text-sm text-dim">Este pipeline possui somente rascunho. Não há execução publicada.</p>}</>:flow&&caps.data.actions.consultStages?<WorkspaceEditor key={`${nome}-${draft?.draftId??'published'}-${experience}`} draft={draft} definition={flow.definition} layout={flow.layout} reasons={flow.readOnlyReasons} capabilities={caps.data} development={development&&!!draft} tab={viewingTab} onSaved={saved} onDiscarded={()=>{client.invalidateQueries({queryKey:['workspace-context',token,nome]});navigate('/pipelines')}}/>:<p className="text-sm text-dim">A definição do fluxo não está disponível neste contexto.</p>}
 </div>
}
